linuxdeepin/deepin-system-upgrade

- src/deepin-system-upgrade-tool/src/tool/main.cpp
Enable HiDPI support
Fixes linuxdeepin/developer-center#3851
> fix: fix blurry application icon display

- src/deepin-system-upgrade-daemon/configs/config.yaml
- src/deepin-system-upgrade-daemon/pkg/application/manager.go
- src/deepin-system-upgrade-daemon/pkg/iso/manager.go
dde-session-shell have been removed when system is migarating. so, system goes to black screen after reoot. I have modified the conditon of installing package to avoid removing important packages.
Log: modify the conditon of installing packages
issue: https://github.com/linuxdeepin/developer-center/issues/3855
> fix: system goes to black screen after reboot

- src/deepin-system-upgrade-daemon/configs/config.yaml
- src/deepin-system-upgrade-daemon/pkg/iso/manager.go
- src/deepin-system-upgrade-daemon/pkg/module/disk/disk_test.go
- src/deepin-system-upgrade-daemon/pkg/module/disk/diskinfo.go
disk check not correct
Log: modify disk check rules
Issue: https://github.com/linuxdeepin/developer-center/issues/3857
> fix: disk check passed but backup current system failed

- src/deepin-system-upgrade-tool/src/tool/image_preparation/checkimageresultwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/imagedownloadwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/retrieveimagemethodwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwarecheckprogresswidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.h
- src/deepin-system-upgrade-tool/src/tool/initialwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_check/upgradecheckprogresswidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_check/upgradecheckresultwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_progress/backupwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_progress/restorationwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_progress/restorationwidget.h
- src/deepin-system-upgrade-tool/src/tool/upgrade_progress/upgradewidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/baselabel.cpp
- src/deepin-system-upgrade-tool/src/widgets/baselabel.h
- src/deepin-system-upgrade-tool/src/widgets/checkresultwidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/errormessagewidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/errormessagewidget.h
- src/deepin-system-upgrade-tool/src/widgets/spinnerwidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/storageresultwidget.cpp
using DFontSizeManager class to enable font scaling
Log: add font scaling
Issue: https://github.com/linuxdeepin/developer-center/issues/3825
> fix: modify font scaling

- src/deepin-system-upgrade-daemon/configs/backup.yaml
- src/deepin-system-upgrade-daemon/configs/config.yaml
- src/deepin-system-upgrade-daemon/configs/upgrade.yaml
- src/deepin-system-upgrade-daemon/pkg/application/manager.go
- src/deepin-system-upgrade-daemon/pkg/module/config/config.go
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/core/dbusworker.cpp
- src/deepin-system-upgrade-tool/src/core/dbusworker.h
- src/deepin-system-upgrade-tool/src/tool/image_preparation/checkimageresultwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/checkimagewidget.h
- src/deepin-system-upgrade-tool/src/tool/image_preparation/imagepreparationwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/imagepreparationwidget.h
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationofflinewidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationofflinewidget.h
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.h
- src/deepin-system-upgrade-tool/src/tool/initialwidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/borderradiusheaderview.cpp
- src/deepin-system-upgrade-tool/src/widgets/borderradiusheaderview.h
- src/deepin-system-upgrade-tool/src/widgets/iconlabel.cpp
- src/deepin-system-upgrade-tool/src/widgets/softwaretablewidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/softwaretablewidget.h
modify the software evaluation interface and application migration process, from the full application migration to the user can choose the application to be migrated
Log: modify software evaluation windows
Issue: https://github.com/linuxdeepin/developer-center/issues/3882
> feat: modify application migration logic

- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/tool/upgrade_progress/systemupgradewidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/alertdialog.cpp
- src/deepin-system-upgrade-tool/src/widgets/alertdialog.h
Add a bullet box before restarting the system after the system backup is completed
Log: add dialog
Issue: https://github.com/linuxdeepin/developer-center/issues/3968
> feat: add dialog before restart

- src/deepin-system-upgrade-daemon/configs/config.yaml
modify the iso address for downloading
Log:
> chore: modify iso address

- debian/changelog
modify changelog for releasing tags
Log:
> chore: bump version to 6.0.2.4

- src/deepin-system-upgrade-daemon/pkg/application/manager.go
> fix: progress value error

- src/deepin-system-upgrade-daemon/configs/config.yaml
install deepin-system-upgrade packages in V23 in advance
Log:
> fix: install deepin-system-upgrade in V23

- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/tool/initialwidget.cpp
> chore: modify title

- src/deepin-system-upgrade-daemon/pkg/checker/manager.go
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/tool/upgrade_check/conditionchecklistwidget.cpp
add translation
Issue: https://github.com/linuxdeepin/developer-center/issues/4170
> fix: chinese string not be translated

- src/deepin-system-upgrade-daemon/configs/config.yaml
> chore: modify iso download url

- src/deepin-system-upgrade-tool/misc/deepin-system-upgrade-tool.desktop
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/core/dbusworker.cpp
- src/deepin-system-upgrade-tool/src/tool/initialwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/main.cpp
- src/deepin-system-upgrade-tool/src/tool/mainwindow.cpp
> chore: modify program name

- src/deepin-system-upgrade-daemon/pkg/application/manager.go
can not send notify, because the deepin-system-upgrade has been removed
Log: not purge package
Issue: https://github.com/linuxdeepin/developer-center/issues/4405
> fix: not send notify

- debian/changelog
> chore: bump version to 6.0.5

- debian/changelog
- src/deepin-system-upgrade-daemon/configs/backup.yaml
- src/deepin-system-upgrade-daemon/configs/upgrade.yaml
- src/deepin-system-upgrade-daemon/pkg/version/manager.go
/boot partition free space overflow
Log: not backup /boot/efi
Issue: https://github.com/linuxdeepin/developer-center/issues/4168
> fix: upgrade failed in multi-system mode

- src/deepin-system-upgrade-daemon/pkg/version/manager.go
After the system upgraded, delete residual files to release space
> chore: delete residual files

- src/deepin-system-upgrade-daemon/pkg/iso/manager.go
- src/deepin-system-upgrade-daemon/pkg/version/manager.go
cannot rollback system in multi-kernels
> fix: rollback failed

- debian/changelog
modify version number to 6.0.7
> chore: modify version number

- src/deepin-system-upgrade-tool/src/tool/upgrade_check/conditionchecklistwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/upgrade_check/upgradecheckprogresswidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/storageresultwidget.cpp
the font show missing when judge the font size in system
Log: modify space between font
Issue: https://github.com/linuxdeepin/developer-center/issues/4170
> fix: fix the font

- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
Bug: https://github.com/linuxdeepin/developer-center/issues/4815
Log: 修复清理对话框还需要清理的空间的提示错误
> fix: 修复清理对话框还需要清理的空间的提示错误

- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_en.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_HK.ts
- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_TW.ts
- src/deepin-system-upgrade-tool/src/tool/upgrade_check/conditionchecklistwidget.cpp
Bug: https://github.com/linuxdeepin/developer-center/issues/4815
Log: Fix storage cleanup text description
> fix: Fix storage cleanup text description

- src/deepin-system-upgrade-daemon/configs/config.yaml
update iso url to Beta2
Log: modify url
> chore: modify iso url

- debian/changelog
> chore: tag 6.0.9

- src/deepin-system-upgrade-daemon/configs/config.yaml
- src/deepin-system-upgrade-tool/src/tool/main.cpp
> fix: modify iso address

- src/deepin-system-upgrade-tool/misc/translations/deepin-system-upgrade-tool_zh_CN.ts
add the translation of the decription
Issue: https://github.com/linuxdeepin/developer-center/issues/7320
> fix: the decription isn't translated in about dialog

- src/deepin-system-upgrade-tool/src/core/dbusworker.cpp
set the timeout of notification to 5s
Issue: https://github.com/linuxdeepin/developer-center/issues/4784
> fix: The notification doesn't disappear automatically

- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.cpp
- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.h
- src/deepin-system-upgrade-tool/src/widgets/iconlabel.cpp
- src/deepin-system-upgrade-tool/src/widgets/iconlabel.h
Issue: https://github.com/linuxdeepin/developer-center/issues/7322
> fix: 评估界面部分应用显示不全

- src/deepin-system-upgrade-daemon/pkg/iso/manager.go
Copy v20 default locale to new system
Issue: https://github.com/linuxdeepin/developer-center/issues/7319, https://github.com/linuxdeepin/developer-center/issues/7328
Log: Losing language setting after upgrade
> fix: Losing language setting after upgrade

- src/deepin-system-upgrade-tool/src/tool/image_preparation/softwareevaluationwidget.cpp
- src/deepin-system-upgrade-tool/src/widgets/iconlabel.cpp
- src/deepin-system-upgrade-tool/src/widgets/iconlabel.h
Issue: https://github.com/linuxdeepin/developer-center/issues/7516, https://github.com/linuxdeepin/developer-center/issues/7509
> fix: 部分图标未居中

- debian/changelog
> bump to 6.0.11

- debian/changelog
- src/deepin-system-upgrade-daemon/configs/config.yaml
Update image download URL to RC2 image
Log: Use RC2 image
> chore: Use RC2 image for online update
